#!/bin/bash
curl http://GGGenome.dbcls.jp/hg19/GCGACAGAGCGAGACTCC.bed>> output.txt
echo PRKDC-E2-E3-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAAATTCCCCAATGAGAAAGG.bed>> output.txt
echo PRKDC-E4-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCTAATGTTATATTTTCCACAGC.bed>> output.txt
echo PRKDC-E4-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTATCCTTCCCCAAACACATCAC.bed>> output.txt
echo PRKDC-E5-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGACAGATGCACTGAGATAGAGG.bed>> output.txt
echo PRKDC-E5-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTATTCGACTGTAAAATAAGACCTTGG.bed>> output.txt
echo PRKDC-E6-E7-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCATAAAACTTAGGAAAGAATGCAG.bed>> output.txt
echo PRKDC-E6-E7-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATGTCATCATCAGGGGAACTC.bed>> output.txt
echo PRKDC-E8-E9-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTGGATGGAATGATGAAAG.bed>> output.txt
echo PRKDC-E8-E9-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCTCCCTGTAAATAACTGTGTG.bed>> output.txt
echo PRKDC-E10-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATCTTCCTGAGCACAGTGTTGAC.bed>> output.txt
echo PRKDC-E10-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAAATCTGGCATCTCCCTAGC.bed>> output.txt
echo PRKDC-E11-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCTTCTCTAGGAAAAATGTATCAC.bed>> output.txt
echo PRKDC-E11-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTCACGCCCATGTTATTCAAG.bed>> output.txt
echo PRKDC-E12-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATCACGCCATTGCACTCC.bed>> output.txt
echo PRKDC-E12-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTCCCAACAGTGCCTACAC.bed>> output.txt
echo PRKDC-E13-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTAAGCAGCAGGTTAGATGACAAAC.bed>> output.txt
echo PRKDC-E13-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAAAATTTAGGAGTTCAAAAGTTGTG.bed>> output.txt
echo PRKDC-E14-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/TGAGAGGTAAAGTTGGGTTCC.bed>> output.txt
echo PRKDC-E14-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCATTGCTAATAACTAAGAAAAGAACG.bed>> output.txt
echo PRKDC-E15-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTATGGGTGGCAGTTTAATTTAG.bed>> output.txt
echo PRKDC-E15-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATTCTAACTTCCTGATTCATACGG.bed>> output.txt
echo PRKDC-E16-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTGCAGTTTATCATCACTGTTTC.bed>> output.txt
echo PRKDC-E16-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAGTTCTCCTCTACAAATGTGC.bed>> output.txt
echo PRKDC-E17-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCACCCATCTTGGTCTTTC.bed>> output.txt
echo PRKDC-E17-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTGATCTCCTGACCTCGTG.bed>> output.txt
echo PRKDC-E18-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATACCTCAAAATGTTACGTGATG.bed>> output.txt
echo PRKDC-E18-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTTAAAACTGCATAGGCCACAATC.bed>> output.txt
echo PRKDC-E19-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATGTTGGTAACTTGAAATGGATTC.bed>> output.txt
echo PRKDC-E19-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGGATTAAGGGCATGAGC.bed>> output.txt
echo PRKDC-E20-21-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGTCATGTCAATAAAGGCTACG.bed>> output.txt
echo PRKDC-E20-21-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACTGGGCTTAAATTTCAGAAG.bed>> output.txt
echo PRKDC-E22-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTTTTGGCAGACAGTGATG.bed>> output.txt
echo PRKDC-E22-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGAGCTCAAGCGATCCAC.bed>> output.txt
echo PRKDC-E22-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGGAGTCAGACACTTCCCAAG.bed>> output.txt
echo PRKDC-E22-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTGGGATTACAGGTGTGC.bed>> output.txt
echo PRKDC-E23-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGCGGTTCTAGGAAATGGAC.bed>> output.txt
echo PRKDC-E23-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATACAGTCAAACCATTAGGCAAG.bed>> output.txt
echo PRKDC-E24-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAATGTAGAACAGCTGGCATTAG.bed>> output.txt
echo PRKDC-E24-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCAGCCCAATTACCTATTAAG.bed>> output.txt
echo PRKDC-E25-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGCAATGAAATTTTTCTTCTTAAAGG.bed>> output.txt
echo PRKDC-E25-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTATCGTTCCTAACCATCTCCAG.bed>> output.txt
echo PRKDC-E26-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGCTATTCTGGAGGTTGAGGTG.bed>> output.txt
echo PRKDC-E26-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATCACTTGAGGTCAGGACTAAGAC.bed>> output.txt
echo PRKDC-E27-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATTCTGGATACACTATGGAGATTG.bed>> output.txt
echo PRKDC-E27-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGAAGACAGCACAGCATCC.bed>> output.txt
echo PRKDC-E28-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGTGCCTTCTTTAATTCCATTC.bed>> output.txt
echo PRKDC-E28-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTTATAAGAGAATCACACGAGC.bed>> output.txt
echo PRKDC-E29-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTTTCAGTTAAAAATTAGGCCAACAC.bed>> output.txt
echo PRKDC-E29-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACTTCCACACATTCCTTGTTTAG.bed>> output.txt
echo PRKDC-E30-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATGAGTTTATGATTTCTAGAGCCTTG.bed>> output.txt
echo PRKDC-E30-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGATCATTCAGACTTAGGATGCTG.bed>> output.txt
echo PRKDC-E31-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGTGAAACAAGTTGAATGCGTAG.bed>> output.txt
echo PRKDC-E31-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATCATGTCGCTGGGATTC.bed>> output.txt
echo PRKDC-E32-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACTTTCCATCAATGTGTCCTTTG.bed>> output.txt
echo PRKDC-E32-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAAAGCTGGGTTGAGAGGATG.bed>> output.txt
echo PRKDC-E33-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTCAGGCAGAAGTTCCCAAC.bed>> output.txt
echo PRKDC-E33-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTCCCTGAGGAAGCAGGAG.bed>> output.txt
echo PRKDC-E34-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATGCTAGCTTAGTGCGTGTG.bed>> output.txt
echo PRKDC-E34-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGCATGCTCAATACATAAAGGAC.bed>> output.txt
echo PRKDC-E35-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTGTCAGTGCTATCTGAAGTGG.bed>> output.txt
echo PRKDC-E35-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAAATCATACAATACTTGTCCAG.bed>> output.txt
echo PRKDC-E36-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAATCCAGGCTTCACATATCAGG.bed>> output.txt
echo PRKDC-E36-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTGCAGTCAGCAGAGATCG.bed>> output.txt
echo PRKDC-E37-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTAAAGTGTACCTCAAATCAAACTCG.bed>> output.txt
echo PRKDC-E37-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAAACCAATGAGCTTTTGGAG.bed>> output.txt
echo PRKDC-E38-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAATTTAAACATTTGAGCAATGG.bed>> output.txt
echo PRKDC-E38-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTAGTCTCCCTACATTTGAACAC.bed>> output.txt
echo PRKDC-E39-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATAATGCTTTATTTGCAATGTCTTAC.bed>> output.txt
echo PRKDC-E39-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGGTTTACAACTTCTCTGATTGTG.bed>> output.txt
echo PRKDC-E40-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTATTTGTTAAGTCTGTGAAATTCTGG.bed>> output.txt
echo PRKDC-E40-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGCCTTATTTATACTCTTCCTCTAGC.bed>> output.txt
echo PRKDC-E41-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGATAAAAGTAGTATGGTTCATGTGC.bed>> output.txt
echo PRKDC-E41-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACACTCCTTGAACAGCAGAG.bed>> output.txt
echo PRKDC-E42-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAGTGATTTAGCATTTTTGACTG.bed>> output.txt
echo PRKDC-E42-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAATACACCCTAAATTAACGC.bed>> output.txt
echo PRKDC-E43-E44-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTCGAGAAAGGCTGAATG.bed>> output.txt
echo PRKDC-E43-E44-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAACCACATGAAACCACCAG.bed>> output.txt
echo PRKDC-E45-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGTGGGAATCTGCAGGAAG.bed>> output.txt
echo PRKDC-E45-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGAGACCTTTCTATGCAGCTAAG.bed>> output.txt
echo PRKDC-E46-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGTTAATAATCACTGGCTTGATG.bed>> output.txt
echo PRKDC-E46-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAATGGACAGAGAACTGGCTTC.bed>> output.txt
echo PRKDC-E47-E48-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTAAGTGTTTGTTATATGCTGTTGC.bed>> output.txt
echo PRKDC-E47-E48-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTCTGCCCCTTTATATTTTCC.bed>> output.txt
echo PRKDC-E49-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTACCTCGCTTTTGGCTTTAG.bed>> output.txt
echo PRKDC-E49-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAAACCATAGCACAGTCAGTG.bed>> output.txt
echo PRKDC-E50-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACAGGGCTTTCAACAGGAG.bed>> output.txt
echo PRKDC-E50-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGGAGGCTGTGGTTTTATTAG.bed>> output.txt
echo PRKDC-E51-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACTCCAAGACTCCGTCTCAG.bed>> output.txt
echo PRKDC-E51-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATTTGTAGCATGGGTCTGG.bed>> output.txt
echo PRKDC-E52-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACCCTTACGTACATGCTGATG.bed>> output.txt
echo PRKDC-E52-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCATTTTGTTTCTAATACCATACAAG.bed>> output.txt
echo PRKDC-E53-E54-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTCAGTGTAGACCAGCAGACATC.bed>> output.txt
echo PRKDC-E53-E54-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGTATATCATGGAAACCCACAG.bed>> output.txt
echo PRKDC-E55-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGTGTAGGGTAGCACATGAAG.bed>> output.txt
echo PRKDC-E55-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACTGCAGTGACCTGTGTTTG.bed>> output.txt
echo PRKDC-E56-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGCAAGCTGTGATTTGGAG.bed>> output.txt
echo PRKDC-E56-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAAGCAGAGAAAATGCTAATACTGC.bed>> output.txt
echo PRKDC-E57-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGGTTTCCCTCTCTGTTAAGC.bed>> output.txt
echo PRKDC-E57-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAATCTAGTGGAGGCCAAGAG.bed>> output.txt
echo PRKDC-E58-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTATGGTACAAATATGCTGATGG.bed>> output.txt
echo PRKDC-E58-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAATGACATCTTCCTTGGGTTC.bed>> output.txt
echo PRKDC-E59-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTTACAAATGGGGACACTGC.bed>> output.txt
echo PRKDC-E59-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATTACGAATGAGAAGGAAACATG.bed>> output.txt
echo PRKDC-E60-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCACCTGTAGGTTTTGTCTTTG.bed>> output.txt
echo PRKDC-E60-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACATTGGAGGCAGTGTCTG.bed>> output.txt
echo PRKDC-E61-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTCTGCGAGCATCAGTTC.bed>> output.txt
echo PRKDC-E61-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTTATACCAAGTCCACCGTTG.bed>> output.txt
echo PRKDC-E62-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTTGTCAATGCCTGCTAAG.bed>> output.txt
echo PRKDC-E62-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACCAGGTTATCAAGAGTCTCAAC.bed>> output.txt
echo PRKDC-E63-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGTGCTTTTCTTGCTTTAAATTG.bed>> output.txt
echo PRKDC-E63-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAATGGTACTCAGCCTGAAAGAC.bed>> output.txt
echo PRKDC-E64-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCACATCTGAATAATTTCTGGC.bed>> output.txt
echo PRKDC-E64-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAACAAGGATCTGCTGTACCTC.bed>> output.txt
echo PRKDC-E65-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTTCTCTTTTCTCTCTCCTTTC.bed>> output.txt
echo PRKDC-E65-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATGCAATTCCCTAGTGCTTC.bed>> output.txt
echo PRKDC-E66-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGTTTCAGACATCAAACATCATC.bed>> output.txt
echo PRKDC-E66-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGAAAGAAGGAAATAGGTGGTATG.bed>> output.txt
echo PRKDC-E67-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGATGTTAGGATTGTTAAAACTTGG.bed>> output.txt
echo PRKDC-E67-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGCCCTGATGCCTAGAACTC.bed>> output.txt
echo PRKDC-E68-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCCATCTTTATTCTCTGTCCTTAAGC.bed>> output.txt
echo PRKDC-E68-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTACATGGGAAACAGGAAGG.bed>> output.txt
echo PRKDC-E69-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATGGTGCCACTGCACTC.bed>> output.txt
echo PRKDC-E69-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACCTACCAATTATTTTAAGGTTCAG.bed>> output.txt
echo PRKDC-E70-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATTCGCTACTCTAAGGTGGATTG.bed>> output.txt
echo PRKDC-E70-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTATCATTCTCTGGCTCACTTTG.bed>> output.txt
echo PRKDC-E71-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CGAGACCCTATCCCAAAAAC.bed>> output.txt
echo PRKDC-E71-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAAATTGGCTGTGCATAACTG.bed>> output.txt
echo PRKDC-E72-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATAGCTTCAGTGTTATTTTGGAG.bed>> output.txt
echo PRKDC-E72-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTCAAGTGATCCACTGCAC.bed>> output.txt
echo PRKDC-E73-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGAACAATGACACTACAAAATACAAG.bed>> output.txt
echo PRKDC-E73-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTATAATACATGCACTGCACAC.bed>> output.txt
echo PRKDC-E74-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAGAAGAGAGCTAGGGGATG.bed>> output.txt
echo PRKDC-E74-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGCAGAATGTTTTGTTAGCAGTG.bed>> output.txt
echo PRKDC-E75-E76-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTTCTTGCTTCATTTAACATTG.bed>> output.txt
echo PRKDC-E75-E76-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATGAGACCTAAAGCATTCAACAG.bed>> output.txt
echo PRKDC-E77-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAGAGAAGAAACATATACCATTG.bed>> output.txt
echo PRKDC-E77-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTCAATATCCCAGTATCACTATTCCAG.bed>> output.txt
echo PRKDC-E78-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATGATCTGCTCGCCTTG.bed>> output.txt
echo PRKDC-E78-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATGGGCCGTTGTCTCATATAC.bed>> output.txt
echo PRKDC-E79-E80-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTCTTTGGCACTGTCTTCAG.bed>> output.txt
echo PRKDC-E79-E80-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTTATTGACCCAGCCAGCAG.bed>> output.txt
echo PRKDC-E81-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAATGAATTCTTGGTGATCTTTGC.bed>> output.txt
echo PRKDC-E81-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAATAATCTTGATGATCTCTCTGAGG.bed>> output.txt
echo PRKDC-E82-E83-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCATGTTTTCTTTTGATTCTTAGC.bed>> output.txt
echo PRKDC-E83-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATTCAATGACCATGACAAAACG.bed>> output.txt
echo PRKDC-E84-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGTAGCTGATTTCAAGGGAAGC.bed>> output.txt
echo PRKDC-E84-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATCAACATGACTCAATGCAC.bed>> output.txt
echo PRKDC-E85-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATGGAGTCTGTATGAACAGCTTTG.bed>> output.txt
echo PRKDC-E85-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTCTCTAAGCCCTGCTTTC.bed>> output.txt
echo PRKDC-E86-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CGTGGGGAATGTGTTTGG.bed>> output.txt
echo PRKDC-E86-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACAGCTGTTTCACTAACTTGCAG.bed>> output.txt
echo RAC2-P1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCAGTAACTTGTGTGAATTGC.bed>> output.txt
echo RAC2-P1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGATTGCTTGAGCCAGGAC.bed>> output.txt
echo RAC2-P2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTCAGTTTTCGCATCAGG.bed>> output.txt
echo RAC2-P2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTGGGAGGCTCACTTCC.bed>> output.txt
echo RAC2-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCACCTGGTACTGTGCCTG.bed>> output.txt
echo RAC2-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCCAAGCTGCCTTCCAG.bed>> output.txt
echo RAC2-E2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGGTGTGAGAACACAGACAGG.bed>> output.txt
echo RAC2-E2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTCTTGGCTGGACTGTCAGG.bed>> output.txt
echo RAC2-E3-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAGTCGCAGACTGTCTCTAGG.bed>> output.txt
echo RAC2-E3-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCTTAAGGGGAGAGGTAGG.bed>> output.txt
echo RAC2-E4-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCTGCCCAGATCCTAAGTCC.bed>> output.txt
echo RAC2-E4-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCTCTGTATGCGACCTCTGC.bed>> output.txt
echo RAC2-E5-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCACCTCTGATCTTCTGG.bed>> output.txt
echo RAC2-E5-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAAGTGCACAGCACAGC.bed>> output.txt
echo RAC2-E6-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CGTGGAAGGGGTTGTATGG.bed>> output.txt
echo RAC2-E6-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATCTTTTCCATCACCTCCTG.bed>> output.txt
echo RAG1-P1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAATCCTTGCACCTGCC.bed>> output.txt
echo RAG1-P1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCAGAACCTTTCAACCTGGTC.bed>> output.txt
echo RAG1-P2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGGTGATGAGATTGAAGTTCC.bed>> output.txt
echo RAG1-P2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCATGTGCGAGAGTTTGC.bed>> output.txt
echo RAG1-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGATGTGGAACTGAGGCAC.bed>> output.txt
echo RAG1-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACATTCATTCAAGAAGCACTCC.bed>> output.txt
echo RAG1-E2-F1A>> output.txt
curl http://GGGenome.dbcls.jp/hg19/TTGAGCACCTAATGTATACTGGG.bed>> output.txt
echo RAG1-E2D-SEQ-R3>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCAACATCAGTGCTGGAAG.bed>> output.txt
echo RAG1-E2-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCGATATCCATGCTTCC.bed>> output.txt
echo RAG1-E2-R2B>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATGCTTGTCCAGTGTGGC.bed>> output.txt
echo RAG1-E2-F3>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTCTGTGGAAGAACTGCGG.bed>> output.txt
echo RAG1-E2C-R4>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGTCCCCTGCAGTTACTCC.bed>> output.txt
echo RAG2-P1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACCAACAATAGTGGAAGGTTAGG.bed>> output.txt
echo RAG2-P1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGTTTCTCTGTCTCTGAAATGAGG.bed>> output.txt
echo RAG2-P2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTTGGCTGAACACTTTGC.bed>> output.txt
echo RAG2-P2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTGAGGGAGATACCCAACAGG.bed>> output.txt
echo RAG2-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAACTCCTTCCTTCTGAGCC.bed>> output.txt
echo RAG2-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCACTTGTGACTAACACACTGC.bed>> output.txt
echo RAG2-E2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGCACAGGACATCACACTG.bed>> output.txt
echo RAG2-E2-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAGGTGCGAAGTGACTAGACG.bed>> output.txt
echo RAG2-E3-F1A>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGCTGACGCATGGTGAC.bed>> output.txt
echo RAG2-E3-R1A>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACTGTTTGTGAATGTTGTCTGC.bed>> output.txt
echo RAG2-E3-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCAGACATTAAGCACAGC.bed>> output.txt
echo RAG2-E3D-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/TCGATGATTATTACTGCTTCTGG.bed>> output.txt
echo RMPR-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCACAATGCCTCTGAAAGC.bed>> output.txt
echo RMPR-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CATAGCAAGGCCAAGAACAGC.bed>> output.txt
echo SLC46-P1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGCTGAATGAATGAAAGATAGGG.bed>> output.txt
echo SLC46-P1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTATTAACAGGCTGTCACGTC.bed>> output.txt
echo SLC46-P2-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTGCCCAGATTGGTCTCG.bed>> output.txt
echo SLC46-P2-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATGACCTCACCTGTAAAGTGTGC.bed>> output.txt
echo SLC46-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTGTTATCTGTGGTGTGTCTGG.bed>> output.txt
echo SLC46-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAGTTACCCGCCACTACC.bed>> output.txt
echo SLC46-E2A-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGGTTTAGGGCTCCAAAGG.bed>> output.txt
echo SLC46-E2A-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAAAGTGCACAGTGATCACC.bed>> output.txt
echo SLC46-E2B-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGATAGCCATGACTCTCTATGC.bed>> output.txt
echo SLC46-E2B-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAAAGACACAGGAATGAACC.bed>> output.txt
echo SLC46-E3-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGGATTTACTGGTGAAGAAGG.bed>> output.txt
echo SLC46-E3-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGATTCCAGGAATGAAGCTG.bed>> output.txt
echo SLC46-E4-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGGAGAGCTACCTGGACCAG.bed>> output.txt
echo SLC46-E4-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGGTCCTGAAGTGTCACC.bed>> output.txt
echo STAT5-P1-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTGGGTAGCGGAGAAGG.bed>> output.txt
echo STAT5-P1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CGAGGTCAGAAGTCCACAGG.bed>> output.txt
echo STAT5-P2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCTGGAACTCGGACAGG.bed>> output.txt
echo STAT5-P2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCTTGAAGGACCCGGAC.bed>> output.txt
echo STAT5-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAAACAAAGCAGCATGTGC.bed>> output.txt
echo STAT5-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACACCCACTCAGCACACG.bed>> output.txt
echo STAT5-E1-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCAACCCAAACAAAGCAG.bed>> output.txt
echo STAT5-E1-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCACGCAGCCTTTAAAGC.bed>> output.txt
echo STAT5-E2-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAATATTTACTCTGGTGGATGTAAGG.bed>> output.txt
echo STAT5-E2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCATCCCCTCAATCTAAGATGG.bed>> output.txt
echo STAT5-E3-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCATTGAGTCCATTTCTGTTGG.bed>> output.txt
echo STAT5-E3-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CGTGTAACTCAACAATGCTGGAC.bed>> output.txt
echo STAT5-E4-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGCCTCCTGTGATTCAGG.bed>> output.txt
echo STAT5-E4-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGCCCCTTAGGATGAAGC.bed>> output.txt
echo STAT5-E5-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGTCTTACCCTGGTTGTAGGAG.bed>> output.txt
echo STAT5-E5-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCCGAATGGAAAGTGTGC.bed>> output.txt
echo STAT5-E6-E7-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAGTATCTGAGCCCAGGAG.bed>> output.txt
echo STAT5-E6-E7-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGCTGTCCCAGGATGGAG.bed>> output.txt
echo STAT5-E8-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAAAGCACAGAGCCTTCCTG.bed>> output.txt
echo STAT5-E8-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGATGAGAGGCAGGAAGTGG.bed>> output.txt
echo STAT5-E9-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGCTCTTCACCTCCTGAGC.bed>> output.txt
echo STAT5-E9-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCAGAAGGGCAAACAGG.bed>> output.txt
echo STAT5-E10-E11-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAAACTTCTCTATTTCCTGCTACC.bed>> output.txt
echo STAT5-E10-E11-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGGTCAGTCCATTTTCAGTTTACC.bed>> output.txt
echo STAT5-E12-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCATTTAGATTCTGTGTCTGAGAGG.bed>> output.txt
echo STAT5-E12-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGATTACAAGTGTGAGTCACTGC.bed>> output.txt
echo STAT5-E13-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGCAAGACAAATGTGTGTAACC.bed>> output.txt
echo STAT5-E13-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTGGGTAACTCTCAAGTTGTCC.bed>> output.txt
echo STAT5-E14-E15-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCATTAGGTAAAACTCAGGTAGGC.bed>> output.txt
echo STAT5-E14-E15-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGCCTTATTATGAGTATGTCATGG.bed>> output.txt
echo STAT5-E16-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGAGCCATTATAATGGCAAGC.bed>> output.txt
echo STAT5-E16-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCACTGAATGGTAATTGTGTGG.bed>> output.txt
echo STAT5-E17-E18-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTAGGTGGTTGTGTTCTGTCC.bed>> output.txt
echo STAT5-E17-E18-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGCTCTGGATTCCTTTGACC.bed>> output.txt
echo STAT5-E19-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAGGCTGAGGGCATAGG.bed>> output.txt
echo STAT5-E19-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACAAAGTAAAAACCACCACAGC.bed>> output.txt
echo TBX1-P1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGTCAAGAGGTGGGAGTGG.bed>> output.txt
echo TBX1-P1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGTGAAGCAAACCCTAATTCC.bed>> output.txt
echo TBX1-P2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTGTGCCTTTATGGATAGGAG.bed>> output.txt
echo TBX1-P2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CGATAGGAGGCCTGACTGG.bed>> output.txt
echo TBX1-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGAGGAGCAGATGTCTCAGC.bed>> output.txt
echo TBX1-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCACACTCCTCTTCACCTG.bed>> output.txt
echo TBX1-E2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGTGAGTGGCACCACAGG.bed>> output.txt
echo TBX1-E2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAGCCAGAAGCCTGGAG.bed>> output.txt
echo TBX1-E3-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAGCTCTCGCATTTCTGC.bed>> output.txt
echo TBX1-E3-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCGGAGGATAGGTGTTAGGAG.bed>> output.txt
echo TBX1-E4-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGCTAAGCCAGGAAAGATGG.bed>> output.txt
echo TBX1-E4-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTAAAGAGTTTCATGGTGCAG.bed>> output.txt
echo TBX1-E5-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGAGGGTTCAATCTCACAGG.bed>> output.txt
echo TBX1-E5-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTCGCAGGGACTCTAAAGG.bed>> output.txt
echo TBX1-E6-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTCATCCAGGAAACTCATTGC.bed>> output.txt
echo TBX1-E6-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACAGCCTGCAGGTCTAAGC.bed>> output.txt
echo TBX1-E7-E8-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAGAAAGGCCCTTGGTG.bed>> output.txt
echo TBX1-E8-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCGGAGAGAAGGCTCTTGG.bed>> output.txt
echo TBX1-E9-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAAGAGCCTTCTCTCCGC.bed>> output.txt
echo TBX1-E9-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGCTGTCTACACTGCAACTGC.bed>> output.txt
echo WAS-P1-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAAGCCTTTGAAGATTATGTGC.bed>> output.txt
echo WAS-P1-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCTGGATGATGACAGAGC.bed>> output.txt
echo WAS-P2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GATAGGCGTGGATCACAGG.bed>> output.txt
echo WAS-P2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTCCACTTGACTGCTTAGACC.bed>> output.txt
echo WAS-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACAGATGTGCTAAGCTCTCG.bed>> output.txt
echo WAS-E1-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GAGATGATGGAGAGGGAAAGG.bed>> output.txt
echo WAS-E2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTGCAGCTCTTCCTTTGG.bed>> output.txt
echo WAS-E2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGATTCACTGATCAGGTCTGAGG.bed>> output.txt
echo WAS-E3-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTCCCAAATCCAGACACC.bed>> output.txt
echo WAS-E6-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTATCCATTCACCCACTTACG.bed>> output.txt
echo WAS-E7-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCACTACCTCCATGACCATCC.bed>> output.txt
echo WAS-E7-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACCCATTTACCCACTCAGC.bed>> output.txt
echo WAS-E8-E9-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAGGAGAGGGCAAGAGG.bed>> output.txt
echo WAS-E8-E9-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTGACCAACTCCTGACTGAAGC.bed>> output.txt
echo WAS-E10-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CAGTCAGGAGTTGGTCAGTGG.bed>> output.txt
echo WAS-E10-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGCACTCTCCTCAGTCCTG.bed>> output.txt
echo WAS-E11-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGATAGGGTTGAAAGGTTGGTG.bed>> output.txt
echo WAS-E11-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGCTGATGTCACTATTGGTGG.bed>> output.txt
echo WAS-E12-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCCTCCTCTAGCATGAGACC.bed>> output.txt
echo WAS-E12-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GACTTTGGGGGAAAGGGAC.bed>> output.txt
echo ZAP70-P1-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTAAGGGAGAGTCAATTCAGG.bed>> output.txt
echo ZAP70-P1-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCCCTTGCTCTCCAGTGG.bed>> output.txt
echo ZAP70-P2-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGCTCTGTGTCTCGGTTGG.bed>> output.txt
echo ZAP70-P2-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGATGCGAAGACAGGAAAGG.bed>> output.txt
echo ZAP70-E1-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCATCTCTCAGTCCCATCCTG.bed>> output.txt
echo ZAP70-E2-R2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAGTCCTCCAGCTCTCC.bed>> output.txt
echo ZAP70-E3-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTGGCGAGCTCAGTCTGC.bed>> output.txt
echo ZAP70-E3-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CACCTCTCCAGCTTCCAAAGG.bed>> output.txt
echo ZAP70-E4-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTGCCTAACACGCGCTAG.bed>> output.txt
echo ZAP70-E4-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAAGTCCCTTTGCACATCAG.bed>> output.txt
echo ZAP70-E5-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAAGGCTCTGAGGTGTGG.bed>> output.txt
echo ZAP70-E7-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CTTCCGCTCCACAGGCAC.bed>> output.txt
echo ZAP70-E8-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCTGTGGAGCGGAAGAAGC.bed>> output.txt
echo ZAP70-E8-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCAAGGCCAAGTGTGCTCC.bed>> output.txt
echo ZAP70-E9-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GGACGGCACCCTTGTCTG.bed>> output.txt
echo ZAP70-E9-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/CCAGTGGACTCAGGGATCG.bed>> output.txt
echo ZAP70-E10-F1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTTCCCGGTGAGCGATCC.bed>> output.txt
echo ZAP70-E10-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGGACTGAGGGTTAGCTCTG.bed>> output.txt
echo ZAP70-E11-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/TGGGTCAGAGAAGCATGCT.bed>> output.txt
echo ZAP70-E12-E13-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GCTTTGGGTGAGATGACATTGG.bed>> output.txt
echo ZAP70-E14-F2>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTCTACCTCAGCCAAGCACAG.bed>> output.txt
echo ZAP70-E14-R1>> output.txt
curl http://GGGenome.dbcls.jp/hg19/GTGATCTACGCCTGACCACC.bed>> output.txt

